version: "3.9"
services:
  mySql:
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: spring-security-acl
      MYSQL_USER: spring-security-acl
      MYSQL_PASSWORD: spring-security-acl
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'